version: '2.1'

services:
  slr_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slr-server
    restart: always
    ports:
      - "48888:48888"
    volumes:
      - logs:/slr-server/logs
      - data:/slr-server/data
    extra_hosts:
      - "docker:10.0.0.90"
      - "one:10.0.0.91"
      - "two:10.0.0.92"
      - "three:10.0.0.93"
    mem_limit: 8g

volumes:
  data:
  logs: