version: '3'

services:
  slr-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slr-server
    restart: always
    ports:
      - "48888:48888"
    volumes:
      - logs:/slr-server/logs
      - data:/slr-server/data
    extra_hosts:
      - "docker:10.0.0.95"
      - "one:10.0.0.98"
      - "two:10.0.0.99"
      - "three:10.0.0.93"
    deploy:
      resources:
        limits:
          memory: 9g

volumes:
  data:
  logs: