spring:
  redis:
    database: 0
    password: Rongshu@2024
    timeout: 5000
    cluster:
      max-redirects: 3
      nodes:
        - localhost:6381
        - localhost:6382
        - localhost:6383
        - localhost:6384
        - localhost:6385
        - localhost:6386
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  kafka:
    producer:
      bootstrap-servers: localhost:9096,localhost:9097,localhost:9098
    consumer:
      bootstrap-servers: localhost:9096,localhost:9097,localhost:9098
      group-id: slr_connector

slr-connector:
  kafka:
    source_topic: slr_event