spring:
  ############################## [数据源 配置项] ##############################
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: lbs # 控制台管理用户名和密码
        login-password: Rongshu@2024
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 5 # 初始连接数
        min-idle: 10 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      primary: master
      datasource:
        master:
          url: jdbc:mysql://windows:3308/starlink_risk_local?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          username: lbs
          password: Rongshu@2024
        slave:
          url: jdbc:mysql://windows:9030/starlink_risk_local?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
          username: root
          password: Rongshu@2024
  ############################## [redis 配置项] ##############################
  redis:
    database: 0
    password: Rongshu@2024
    namespace: starlink_risk_local
    timeout: 5000
    cluster:
      max-redirects: 3
      nodes:
        - windows:6381
        - windows:6382
        - windows:6383
        - windows:6384
        - windows:6385
        - windows:6386
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  ############################## [kafka 配置项] ##############################
  kafka:
    producer:
      bootstrap-servers: windows:9096,windows:9097,windows:9098
    consumer:
      bootstrap-servers: windows:9096,windows:9097,windows:9098
      group-id: starlink_risk_server_local
  data:
    ############################## [mongo 配置项] ##############################
    mongodb:
      host: windows
      port: 27018
      username: root
      password: Rongshu@2024
      database: starlink_risk_local
      authentication-database: admin

############################## [xxl-job 配置项] ##############################
xxl:
  job:
    admin:
      addresses: http://windows:8181/xxl-job-admin
    accessToken: Rongshu@2024
    executor:
      appname: starlink-risk-local
      address:
      ip:
      port: 9999
      logpath: C:/Me/Temp/xxl-job/jobhandler
      logretentiondays: 30

############################## [日志 配置项] ##############################
logging:
  file:
    name: /slr-server/logs/server.log # 日志文件名，全路径

debug: false

############################## [项目配置项] ##############################
slr-server:
  active: local
  kafka:
    event:
      topic: starlink_risk_event_local
      partition: 6
      replica: 3
    alert:
      topic: starlink_risk_alert_local
      partition: 6
      replica: 3
  file-path:
    event-log: C:/Me/Temp/mock/event.log
  api-address:
    rso-alert: http://10.152.130.129:8081/rso/messagePush/sendWarningMsg
    slr-gif: http://windows:48881/slr_event_local.gif
