server:
  port: 48887

spring:
  ############################## [数据源 配置项] ##############################
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 排除 Druid 的自动配置，使用 dynamic-datasource-spring-boot-starter 配置多数据源
  datasource:
    druid: # Druid 【监控】相关的全局配置
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: lbs # 控制台管理用户名和密码
        login-password: Rongshu@2024
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 100
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
    dynamic: # 多数据源配置
      druid: # Druid 【连接池】相关的全局配置
        initial-size: 5 # 初始连接数
        min-idle: 10 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 600000 # 配置获取连接等待超时的时间，单位：毫秒
        time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位：毫秒
        validation-query: SELECT 1 # 配置检测连接是否有效
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      primary: master
      datasource:
        master:
          url: jdbc:mysql://10.188.60.4:53376/dmdev?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
          username: dmdev
          password: Dmdev_1234
        slave:
          url: jdbc:mysql://10.191.200.124:9030/startlink_risk_dev?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
          username: rsmall
          password: Rsmall@123bdas
  ############################## [redis 配置项] ##############################
  redis:
    database: 0
    password: common@Iml8329
    namespace: starlink_risk_dev
    timeout: 5000
    cluster:
      max-redirects: 3
      nodes: 10.152.143.221:50022,10.152.143.222:50022,10.152.143.223:50022,10.152.143.221:50023,10.152.143.222:50023,10.152.143.223:50023
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  ############################## [kafka 配置项] ##############################
  kafka:
    producer:
      bootstrap-servers: 10.152.143.105:9092,10.152.143.106:9092,10.152.143.107:9092
    consumer:
      bootstrap-servers: 10.152.143.105:9092,10.152.143.106:9092,10.152.143.107:9092
      group-id: starlink_risk_server_dev
  data:
    ############################## [mongo 配置项] ##############################
    mongodb:
      host: 10.152.143.163
      port: 54257
      username: starlink_risk_dev # root
      password: DawnImp0513 # DawnImp@0513
      database: starlink_risk_dev
      authentication-database: starlink_risk_dev

############################## [日志 配置项] ##############################
logging:
  file:
    name: /app/lbs/project/slr/log/server.log # 日志文件名，全路径

debug: false

############################## [项目配置项] ##############################
slr-server:
  active: dev
  kafka:
    event:
      topic: starlink_risk_event_dev
      partition: 6
      replica: 3
    alert:
      topic: starlink_risk_alert_dev
      partition: 6
      replica: 3
  file-path:
    event-log: /app/lbs/project/slr/data/event.log
  api-address:
    rso-alert: http://10.189.18.32:8081/rso/messagePush/sendWarningMsg
    slr-gif: http://10.188.6.154:48881/slr_event_dev.gif