# define
slr-test.sources=r1
slr-test.sinks=k1
slr-test.channels=c1
# source
slr-test.sources.r1.type=TAILDIR
slr-test.sources.r1.positionFile=/home/lbs/software/flume/position/taildir_position_test.json
slr-test.sources.r1.filegroups=g1
slr-test.sources.r1.filegroups.g1=/home/lbs/docker/nginx/logs/slr_event_test.*
slr-test.sources.r1.batchSize=1000
slr-test.sources.r1.fileHeader=true
# sink
slr-test.sinks.k1.type=org.apache.flume.sink.kafka.KafkaSink
slr-test.sinks.k1.kafka.bootstrap.servers=one:9092,two:9092,three:9092
slr-test.sinks.k1.kafka.topic=starlink_risk_event_test
slr-test.sinks.k1.kafka.flumeBatchSize=1000
slr-test.sinks.k1.kafka.producer.acks=1
slr-test.sinks.k1.kafka.producer.linger.ms=1000
# channel
slr-test.channels.c1.type=memory
slr-test.channels.c1.capacity=1000000
slr-test.channels.c1.transactionCapacity=2000
# bind
slr-test.sources.r1.channels=c1
slr-test.sinks.k1.channel=c1
