# define
slr.sources = r1
slr.sinks = k1
slr.channels = c1

# source
slr.sources.r1.type = TAILDIR
slr.sources.r1.positionFile=/home/lbs/software/flume/position/taildir_position_loal.json
slr.sources.r1.filegroups = g1
slr.sources.r1.filegroups.g1=/home/lbs/docker/nginx/logs/slr_event_local.*
slr.sources.r1.batchSize=1
slr.sources.r1.fileHeader=true

# sink
slr.sinks.k1.type = org.apache.flume.sink.kafka.KafkaSink
slr.sinks.k1.kafka.bootstrap.servers=one:9092,two:9092,three:9092
slr.sinks.k1.kafka.topic=starlink_risk_event_local
slr.sinks.k1.kafka.flumeBatchSize = 1000
slr.sinks.k1.kafka.producer.acks = 1
slr.sinks.k1.kafka.producer.linger.ms = 1000

# channel
slr.channels.c1.type = memory
slr.channels.c1.capacity=10000
slr.channels.c1.transactionCapacity=2000

# bind
slr.sources.r1.channels = c1
slr.sinks.k1.channel = c1
