# 定义日志格式 slr_event_format，用于记录后端相关的埋点数据
log_format slr_event_format '{"eventTime":"$msec","channel":"$arg_channel","targetField":"$arg_targetField","targetValue":"$arg_targetValue","eventField":"$arg_eventField","eventValue":"$arg_eventValue","eventAttrMap":"$arg_eventAttrMap"}';

# 使用正则表达式从时间中提取日期部分（yyyy-MM-dd），并赋值给变量 $logdate
map $time_iso8601 $logdate {
    '~^(?<ymd>\d{4}-\d{2}-\d{2})' $ymd;  # 匹配时间字符串开头的年月日部分，并赋值
    default 'date-not-found';             # 如果无法匹配，则使用默认值
}

server {
    listen       48881;                      # 监听48881端口
    server_name  127.0.0.1;                  # 设置服务器名称为本地地址
    charset utf-8;                           # 设置字符编码为UTF-8
    client_max_body_size 1m;                 # 设置客户端请求体的最大大小为1MB

    # 静态文件的根目录
    root   /usr/share/nginx/html;             # 设置网站根目录
    index  index.html;                        # 设置默认首页文件

    # 处理自动上报的埋点数据请求（local环境）
    location /slr_event_local.gif {
        log_subrequest on;                                                          # 开启子请求日志记录
        access_log /var/log/nginx/slr_event_local_$logdate.json slr_event_format;   # 设置访问日志文件路径和使用的日志格式
        add_header Expires "Fri, 01 Jan 1980 00:00:00 GMT";                         # 设置响应头，告知客户端资源已过期
        add_header Pragma "no-cache";                                               # 设置响应头，禁用缓存
        add_header Cache-Control "no-cache, max-age=0, must-revalidate";            # 设置响应头，进一步控制缓存行为
        empty_gif;                                                                  # 返回一个1x1像素的透明GIF图片作为响应
    }

    # 处理自动上报的埋点数据请求（test环境）
    location /slr_event_test.gif {
        log_subrequest on;                                                          # 开启子请求日志记录
        access_log /var/log/nginx/slr_event_test_$logdate.json slr_event_format;    # 设置访问日志文件路径和使用的日志格式
        add_header Expires "Fri, 01 Jan 1980 00:00:00 GMT";                         # 设置响应头，告知客户端资源已过期
        add_header Pragma "no-cache";                                               # 设置响应头，禁用缓存
        add_header Cache-Control "no-cache, max-age=0, must-revalidate";            # 设置响应头，进一步控制缓存行为
        empty_gif;                                                                  # 返回一个1x1像素的透明GIF图片作为响应
    }
}
